# Базовый образ
FROM python:3.12-slim

# Обновление pip
RUN python -m pip install --upgrade pip

# Установка рабочей директории
WORKDIR /app

# Копирование requirements.txt первым для оптимизации кэширования
COPY requirements.txt /app/

# Установка зависимостей из requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Копирование остальных файлов проекта
COPY . /app

# Команда по умолчанию
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
